/**
 * Emits dist/tokens.css from the TypeScript tokens so the web app consumes
 * the exact same values as React Native. Run with `npm run tokens`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

// Read the token source directly; keeping this dependency-free avoids adding
// a TS build step just to generate a stylesheet.
const source = await import(`file://${resolve(root, 'src/tokens.ts')}`).catch(() => null);

if (!source) {
  console.error(
    'Could not import src/tokens.ts directly.\n' +
      'Run this through a TS-aware runtime, e.g. `node --experimental-strip-types scripts/build-css.mjs`.',
  );
  process.exit(1);
}

const { lightTheme, darkTheme, spacing, radius, fontSize, duration } = source;

const toVars = (prefix, record, suffix = '') =>
  Object.entries(record)
    .map(([key, value]) => `  --${prefix}-${kebab(key)}: ${value}${typeof value === 'number' ? suffix : ''};`)
    .join('\n');

function kebab(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

const css = `/* Generated by @app/design-tokens — do not edit by hand. */
:root {
${toVars('color', lightTheme)}
${toVars('space', spacing, 'px')}
${toVars('radius', radius, 'px')}
${toVars('font-size', fontSize, 'px')}
${toVars('duration', duration, 'ms')}
}

:root[data-theme='dark'] {
${toVars('color', darkTheme)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${toVars('color', darkTheme).replace(/^/gm, '  ')}
  }
}
`;

mkdirSync(resolve(root, 'dist'), { recursive: true });
writeFileSync(resolve(root, 'dist/tokens.css'), css, 'utf8');
console.log('Wrote dist/tokens.css');
